application: dhshardcode
version: sand
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: .*
  script: main.app 

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- mail





